### ISSUE TITLE
LoadError on `require rails/instrumentation` when installing as root

### ISSUE THREAD

**Issue by fredericgermain** [signalfx/ruby-rails-instrumentation#6]
rb files in data.tar.gz in gem cache files are always 644. Here they are 600. If a user install the gem 1.3.0 as root, it cannot access the file and there is an error.

sudo gem install rails-instrumentation

find /var/lib/gems/ -mount -name instrumentation |xargs ls -l 
total 20
-rw------- 1 root root 1312 avril  3 22:04 patch.rb
-rw------- 1 root root 1233 avril  3 22:04 subscriber.rb
drwxr-xr-x 2 root root 4096 avril  3 22:04 subscribers
-rw------- 1 root root 2053 avril  3 22:04 utils.rb
-rw------- 1 root root   77 avril  3 22:04 version.rb

test.rb file with : `require 'rails/instrumentation'`

ruby test.rb 
Traceback (most recent call last):
        2: from t.rb:1:in `<main>'
        1: from /home/fred/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/fred/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rails/instrumentation (LoadError)

Probably due to file permission being 600 during gem build ?

tar xvf bundles/ruby/2.6.0/cache/rails-instrumentation-0.1.3.gem data.tar.gz --to-stdout | tar ztvf -
data.tar.gz
-rw------- wheel/wheel      73 2019-10-22 16:00 .gitignore
-rw-r--r-- wheel/wheel     587 2019-10-22 16:00 .rubocop.yml
-rw------- wheel/wheel     375 2019-10-22 16:00 Appraisals
-rw-r--r-- wheel/wheel     177 2019-10-22 16:00 Gemfile
-rw------- wheel/wheel   11338 2019-10-22 16:00 LICENSE
-rw------- wheel/wheel    9394 2019-10-22 16:00 README.md
-rw------- wheel/wheel     149 2019-10-22 16:00 Rakefile
-rwx------ wheel/wheel     356 2019-10-22 16:00 bin/console
-rwx------ wheel/wheel     131 2019-10-22 16:00 bin/setup
-rw------- wheel/wheel    2246 2019-10-22 16:00 lib/rails/instrumentation.rb
-rw------- wheel/wheel    1312 2019-10-22 16:00 lib/rails/instrumentation/patch.rb
-rw------- wheel/wheel    1233 2019-10-22 16:00 lib/rails/instrumentation/subscriber.rb
-rw------- wheel/wheel    1859 2019-10-22 16:00 lib/rails/instrumentation/subscribers/action_cable_subscriber.rb
-rw------- wheel/wheel    4760 2019-10-22 16:00 lib/rails/instrumentation/subscribers/action_controller_subscriber.rb
-rw------- wheel/wheel    1912 2019-10-22 16:00 lib/rails/instrumentation/subscribers/action_mailer_subscriber.rb
-rw------- wheel/wheel    1295 2019-10-22 16:00 lib/rails/instrumentation/subscribers/action_view_subscriber.rb
-rw------- wheel/wheel    1378 2019-10-22 16:00 lib/rails/instrumentation/subscribers/active_job_subscriber.rb
-rw-r--r-- wheel/wheel    1187 2019-10-22 16:00 lib/rails/instrumentation/subscribers/active_record_subscriber.rb
-rw------- wheel/wheel    2439 2019-10-22 16:00 lib/rails/instrumentation/subscribers/active_storage_subscriber.rb
-rw------- wheel/wheel    1742 2019-10-22 16:00 lib/rails/instrumentation/subscribers/active_support_subscriber.rb
-rw------- wheel/wheel    2053 2019-10-22 16:00 lib/rails/instrumentation/utils.rb
-rw------- wheel/wheel      77 2019-10-22 16:00 lib/rails/instrumentation/version.rb
-rw-r--r-- wheel/wheel    1476 2019-10-22 16:00 rails-instrumentation.gemspec

**Comment by fredericgermain** [comment]
Would it be possible to have a minor release that fixes these file permissions?

**Comment by fredericgermain** [comment]
Is the project still maintained?

**Comment by rmfitzpatrick** [comment]
@fredericgermain thanks for your report and patience.  I plan on correcting this issue, but haven't had a moment to deduce why the permission issue exists (would want to avoid regressing with future updates).  Please feel free to open a PR if you are able such that the permissions meet your needs, or contact your customer support representative if you are a SignalFx customer for prioritization assistance.

**Comment by fredericgermain** [comment]
Hi @rmfitzpatrick 
Thanks for the comment.

There is anything wrong with the source.

Probably there was something bad permission on publisher sources during publishing of 0.1.3. I have the problem if I change the permission of the checked-out files. The `gem build` step gives actually warning when the permissions are not appropriate. 

Bad :
```
find -type f |xargs chmod 600
fred@thor:~/ruby-rails-instrumentation$ gem build rails-instrumentation.gemspec
WARNING:  licenses is empty, but is recommended.  Use a license identifier from
http://spdx.org/licenses or 'Nonstandard' for a nonstandard license.
WARNING:  .gitignore is not world-readable
WARNING:  .rubocop.yml is not world-readable
WARNING:  Appraisals is not world-readable
WARNING:  Gemfile is not world-readable
WARNING:  LICENSE is not world-readable
WARNING:  README.md is not world-readable
WARNING:  Rakefile is not world-readable
WARNING:  bin/console is not world-readable
WARNING:  bin/setup is not world-readable
WARNING:  lib/rails/instrumentation.rb is not world-readable
WARNING:  lib/rails/instrumentation/patch.rb is not world-readable
WARNING:  lib/rails/instrumentation/subscriber.rb is not world-readable
WARNING:  lib/rails/instrumentation/subscribers/action_cable_subscriber.rb is not world-readable
WARNING:  lib/rails/instrumentation/subscribers/action_controller_subscriber.rb is not world-readable
WARNING:  lib/rails/instrumentation/subscribers/action_mailer_subscriber.rb is not world-readable
WARNING:  lib/rails/instrumentation/subscribers/action_view_subscriber.rb is not world-readable
WARNING:  lib/rails/instrumentation/subscribers/active_job_subscriber.rb is not world-readable
WARNING:  lib/rails/instrumentation/subscribers/active_record_subscriber.rb is not world-readable
WARNING:  lib/rails/instrumentation/subscribers/active_storage_subscriber.rb is not world-readable
WARNING:  lib/rails/instrumentation/subscribers/active_support_subscriber.rb is not world-readable
WARNING:  lib/rails/instrumentation/utils.rb is not world-readable
WARNING:  lib/rails/instrumentation/version.rb is not world-readable
WARNING:  rails-instrumentation.gemspec is not world-readable
WARNING:  open-ended dependency on bundler (>= 1.17, development) is not recommended
  if bundler is semantically versioned, use:
    add_development_dependency 'bundler', '~> 1.17'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: rails-instrumentation
  Version: 0.1.3
  File: rails-instrumentation-0.1.3.gem
tar xvf rails-instrumentation-0.1.3.gem  data.tar.gz --to-stdout | tar ztvf -
data.tar.gz
-rw------- wheel/wheel      73 2020-04-17 11:15 .gitignore
-rw------- wheel/wheel     587 2020-04-17 11:15 .rubocop.yml
-rw------- wheel/wheel     375 2020-04-17 11:15 Appraisals
-rw------- wheel/wheel     177 2020-04-17 11:15 Gemfile
-rw------- wheel/wheel   11338 2020-04-17 11:15 LICENSE
-rw------- wheel/wheel    9394 2020-04-17 11:15 README.md
-rw------- wheel/wheel     149 2020-04-17 11:15 Rakefile
-rw------- wheel/wheel     356 2020-04-17 11:15 bin/console
-rw------- wheel/wheel     131 2020-04-17 11:15 bin/setup
-rw------- wheel/wheel    2246 2020-04-17 11:15 lib/rails/instrumentation.rb
-rw------- wheel/wheel    1312 2020-04-17 11:15 lib/rails/instrumentation/patch.rb
-rw------- wheel/wheel    1233 2020-04-17 11:15 lib/rails/instrumentation/subscriber.rb
-rw------- wheel/wheel    1859 2020-04-17 11:15 lib/rails/instrumentation/subscribers/action_cable_subscriber.rb
-rw------- wheel/wheel    4760 2020-04-17 11:15 lib/rails/instrumentation/subscribers/action_controller_subscriber.rb
-rw------- wheel/wheel    1912 2020-04-17 11:15 lib/rails/instrumentation/subscribers/action_mailer_subscriber.rb
-rw------- wheel/wheel    1295 2020-04-17 11:15 lib/rails/instrumentation/subscribers/action_view_subscriber.rb
-rw------- wheel/wheel    1378 2020-04-17 11:15 lib/rails/instrumentation/subscribers/active_job_subscriber.rb
-rw------- wheel/wheel    1187 2020-04-17 11:15 lib/rails/instrumentation/subscribers/active_record_subscriber.rb
-rw------- wheel/wheel    2439 2020-04-17 11:15 lib/rails/instrumentation/subscribers/active_storage_subscriber.rb
-rw------- wheel/wheel    1742 2020-04-17 11:15 lib/rails/instrumentation/subscribers/active_support_subscriber.rb
-rw------- wheel/wheel    2053 2020-04-17 11:15 lib/rails/instrumentation/utils.rb
-rw------- wheel/wheel      77 2020-04-17 11:15 lib/rails/instrumentation/version.rb
-rw------- wheel/wheel    1476 2020-04-17 11:15 rails-instrumentation.gemspec
```

Good
```
find -type f |xargs chmod 644
fred@thor:~/ruby-rails-instrumentation$ gem build rails-instrumentation.gemspec 
WARNING:  licenses is empty, but is recommended.  Use a license identifier from
http://spdx.org/licenses or 'Nonstandard' for a nonstandard license.
WARNING:  open-ended dependency on bundler (>= 1.17, development) is not recommended
  if bundler is semantically versioned, use:
    add_development_dependency 'bundler', '~> 1.17'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: rails-instrumentation
  Version: 0.1.3
  File: rails-instrumentation-0.1.3.gem
fred@thor:~/ruby-rails-instrumentation$ tar xvf rails-instrumentation-0.1.3.gem  data.tar.gz --to-stdout | tar ztvf -
data.tar.gz
-rw-r--r-- wheel/wheel      73 2020-04-17 11:16 .gitignore
-rw-r--r-- wheel/wheel     587 2020-04-17 11:16 .rubocop.yml
-rw-r--r-- wheel/wheel     375 2020-04-17 11:16 Appraisals
-rw-r--r-- wheel/wheel     177 2020-04-17 11:16 Gemfile
-rw-r--r-- wheel/wheel   11338 2020-04-17 11:16 LICENSE
-rw-r--r-- wheel/wheel    9394 2020-04-17 11:16 README.md
-rw-r--r-- wheel/wheel     149 2020-04-17 11:16 Rakefile
-rw-r--r-- wheel/wheel     356 2020-04-17 11:16 bin/console
-rw-r--r-- wheel/wheel     131 2020-04-17 11:16 bin/setup
-rw-r--r-- wheel/wheel    2246 2020-04-17 11:16 lib/rails/instrumentation.rb
-rw-r--r-- wheel/wheel    1312 2020-04-17 11:16 lib/rails/instrumentation/patch.rb
-rw-r--r-- wheel/wheel    1233 2020-04-17 11:16 lib/rails/instrumentation/subscriber.rb
-rw-r--r-- wheel/wheel    1859 2020-04-17 11:16 lib/rails/instrumentation/subscribers/action_cable_subscriber.rb
-rw-r--r-- wheel/wheel    4760 2020-04-17 11:16 lib/rails/instrumentation/subscribers/action_controller_subscriber.rb
-rw-r--r-- wheel/wheel    1912 2020-04-17 11:16 lib/rails/instrumentation/subscribers/action_mailer_subscriber.rb
-rw-r--r-- wheel/wheel    1295 2020-04-17 11:16 lib/rails/instrumentation/subscribers/action_view_subscriber.rb
-rw-r--r-- wheel/wheel    1378 2020-04-17 11:16 lib/rails/instrumentation/subscribers/active_job_subscriber.rb
-rw-r--r-- wheel/wheel    1187 2020-04-17 11:16 lib/rails/instrumentation/subscribers/active_record_subscriber.rb
-rw-r--r-- wheel/wheel    2439 2020-04-17 11:16 lib/rails/instrumentation/subscribers/active_storage_subscriber.rb
-rw-r--r-- wheel/wheel    1742 2020-04-17 11:16 lib/rails/instrumentation/subscribers/active_support_subscriber.rb
-rw-r--r-- wheel/wheel    2053 2020-04-17 11:16 lib/rails/instrumentation/utils.rb
-rw-r--r-- wheel/wheel      77 2020-04-17 11:16 lib/rails/instrumentation/version.rb
-rw-r--r-- wheel/wheel    1476 2020-04-17 11:16 rails-instrumentation.gemspec

**Comment by rmfitzpatrick** [comment]
@fredericgermain can you confirm this meets your needs?

[rails-instrumentation-0.1.4.pre.0.gem.zip](https://github.com/signalfx/ruby-rails-instrumentation/files/4531139/rails-instrumentation-0.1.4.pre.0.gem.zip)

**Comment by fredericgermain** [comment]
Hi @rmfitzpatrick 

Yes, that one is good :)

**Comment by fredericgermain** [comment]
So it just needs releasing now :)

**Comment by rmfitzpatrick** [comment]
@fredericgermain 0.1.4 has been released.

**Comment by fredericgermain** [comment]
Perfect! Thank you so much!!

**Comment by fredericgermain** [comment]
I confirm it fixes the problem so you can close the ticket

**Comment by rmfitzpatrick** [comment]
Thanks again for your patience and the report @fredericgermain.
